{{- $metricsPort := include "validate.metricsPort" . }}
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "local-storage-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "local-storage-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "local-storage-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: metrics
      port: {{ $metricsPort }}
      targetPort: metrics
{{- end }}
